[package]
name = "qec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blas-src = { version = "0.9.0", features = ["accelerate"] }
mhgl = "0.1.4"
ndarray = { version = "0.15.6", features = ["blas"] }
rand = "0.8.5"
