[package]
name = "qec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blas-src = { version = "0.9.0", features = ["accelerate"] }
ff = { version = "0.13.0", features = ["derive"] }
mhgl = {version = "*", path="/Users/matt/repos/mhgl"}
ndarray = { version = "0.15.6", features = ["blas"] }
ndarray-linalg = { version = "*", path = "../ndarray-linalg/ndarray-linalg" }
rand = "0.8.5"
